import { expect, test } from "@playwright/test";
test("settings work without login, persist, preview and reset", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const audioRequests: string[] = [];
  page.on("request", (request) => { if (request.url().includes("/audio/")) audioRequests.push(request.url()); });
  await page.goto("/settings");
  await expect(page.getByLabel("Battle Animation", { exact: true })).toBeEnabled();
  await page.getByLabel("Battle Animation", { exact: true }).selectOption("cinematic");
  await page.getByLabel("Master Volume", { exact: true }).fill("37");
  await page.getByLabel("High Contrast UI", { exact: true }).check();
  await page.getByLabel("Reduced Motion", { exact: true }).check();
  await expect(page.locator("html")).toHaveAttribute("data-reduced-motion", "true");
  await expect(page.locator("html")).toHaveAttribute("data-screen-shake", "false");
  await page.reload();
  await expect(page.getByLabel("Battle Animation", { exact: true })).toHaveValue("cinematic");
  await expect(page.getByLabel("Master Volume", { exact: true })).toHaveValue("37");
  await expect(page.getByLabel("High Contrast UI", { exact: true })).toBeChecked();
  await page.getByRole("button", { name: "Preview impact" }).click();
  await page.getByRole("button", { name: "Reset to Defaults", exact: true }).click();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByLabel("Master Volume", { exact: true })).toHaveValue("37");
  await page.getByRole("button", { name: "Reset to Defaults", exact: true }).click();
  await page.getByRole("alertdialog").getByRole("button", { name: "Reset to Defaults" }).click();
  await expect(page.getByLabel("Battle Animation", { exact: true })).toHaveValue("standard");
  await expect(page.getByLabel("Confirm End Turn", { exact: true })).toBeDisabled();
  await page.screenshot({ path: testInfo.outputPath("settings-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 844, height: 390 });
  await page.getByLabel("Larger Interface Text", { exact: true }).check();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("settings-landscape.png"), fullPage: true });
  expect(errors).toEqual([]); expect(audioRequests).toEqual([]);
});
test("system motion preference follows the browser until explicitly overridden", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/settings");
  await expect(page.getByLabel("Reduced Motion", { exact: true })).toBeChecked();
  await page.getByLabel("Reduced Motion", { exact: true }).uncheck();
  await page.reload();
  await expect(page.getByLabel("Reduced Motion", { exact: true })).not.toBeChecked();
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await expect(page.getByLabel("Reduced Motion", { exact: true })).not.toBeChecked();
});
